name: run-tests

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: yarn install
      - run: yarn test