name: run-tests

on:
  pull_request:
    branches:
      - main

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: 'latest'
  - run: yarn install
  - run: yarn test